// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxLHrvbsy2HtTsbj6FApKoCn-6XL3OCw',
    appId: '1:176251836848:web:f8e280b9a6cc25fcb45e75',
    messagingSenderId: '176251836848',
    projectId: 'rablodemo-ce24a',
    authDomain: 'rablodemo-ce24a.firebaseapp.com',
    storageBucket: 'rablodemo-ce24a.firebasestorage.app',
    measurementId: 'G-MJ51YQWYQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxodGjkgmy3VYgf0JF7U6_u56VIgJKx38',
    appId: '1:176251836848:android:266d369beca68d8db45e75',
    messagingSenderId: '176251836848',
    projectId: 'rablodemo-ce24a',
    storageBucket: 'rablodemo-ce24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3XYKVWJiEizNVkVJRFRUZ52kPMfkgZbY',
    appId: '1:176251836848:ios:b72046c32d16bb0fb45e75',
    messagingSenderId: '176251836848',
    projectId: 'rablodemo-ce24a',
    storageBucket: 'rablodemo-ce24a.firebasestorage.app',
    iosBundleId: 'com.example.rabloDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3XYKVWJiEizNVkVJRFRUZ52kPMfkgZbY',
    appId: '1:176251836848:ios:b72046c32d16bb0fb45e75',
    messagingSenderId: '176251836848',
    projectId: 'rablodemo-ce24a',
    storageBucket: 'rablodemo-ce24a.firebasestorage.app',
    iosBundleId: 'com.example.rabloDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxLHrvbsy2HtTsbj6FApKoCn-6XL3OCw',
    appId: '1:176251836848:web:5593e6fc1389c86fb45e75',
    messagingSenderId: '176251836848',
    projectId: 'rablodemo-ce24a',
    authDomain: 'rablodemo-ce24a.firebaseapp.com',
    storageBucket: 'rablodemo-ce24a.firebasestorage.app',
    measurementId: 'G-NG50VRDYMF',
  );
}
